author: Laszlo Teveli
author_url: https://tevelee.github.io
readme: README.md

documentation: Documentation/*.md
abstract: Documentation/Sections/*.md

module: Funky
module_version: v1.2

output: Documentation/Output
theme: fullwidth

github_url: https://github.com/tevelee/Funky
github_file_prefix: https://github.com/tevelee/Funky/tree/master

root_url: https://tevelee.github.io/Funky
dash_url: https://tevelee.github.io/Funky/docsets/Funky.xml

clean: true
objc: true
sdk: iphonesimulator

umbrella_header: Example/Pods/Target Support Files/FunkyObjC-iOS/FunkyObjC-iOS-umbrella.h

framework_root: Source
source_directory: .