# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.2.1
language: objective-c
cache: 
- cocoapods
podfile: Example/Podfile
before_install:
- env
- locale
- gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- pod --version
- xcpretty --version
- xcodebuild -version
- xcodebuild -showsdks
- pod setup --silent > /dev/null
- pod repo update --silent
- pod install --project-directory=Example
script:
- set -o pipefail
- xcodebuild clean build -workspace Example/Funky.xcworkspace -scheme Funky-Example -sdk iphonesimulator9.3 -configuration Release | xcpretty -c
- xcodebuild test -workspace Example/Funky.xcworkspace -scheme Funky-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -c
- pod lib lint --allow-warnings
after_success:
  - bash <(curl -s https://codecov.io/bash)
